config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount ActionCable.server => '/cable'

  root 'home#index'
  resources :messages
  resources :home, only: [:index], path: '' do
    collection do
      get 'privacy'
      get 'clear_messages'
      post 'create_subscriber'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :registrations, only: [:create, :update] do
        collection do
          get 'check_login'
        end
      end
      resources :providers
      resources :networks, only: [:index, :create]
      resources :messages do
        collection do
          post 'lock'
          post 'unlock'
          post 'delete'
          post 'sms_sharing'
          get 'legendary_list'
          get 'profile_messages'
          get 'block'
          post 'social_feed'
        end
      end
      resources :networks_users, only: [:index]
      resources :members, only: [:create]
      resources :profiles do
        collection do
          get 'user_by_provider'
          post 'connect_social'
          post 'change_points_count'
          get 'disabled_hero'
        end
      end
      resources :sessions, only: [:create, :destroy] do
        collection do
          post 'oauth_login'
          post 'verification'
        end
      end
      resources :user_likes, only: [:create]
      resources :legendary_likes, only: [:create, :index]
      resources :invitations, only: [:create]
      resources :contacts, only: [:create]
      get '/sms', to: 'invitations#sms'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :check_token

  def index
    @subscriber = Subscriber.new
  end

  def create_subscriber
    @subscriber = Subscriber.find_by(email: params[:subscriber][:email])
    if @subscriber.present?
      flash[:notice] = "User already exist..."
      redirect_to root_path
    else
      @subscriber = Subscriber.new(subscriber_params)
      if @subscriber.save
        flash[:notice] = "Successfully subscribed..."
        redirect_to root_path
      else
        flash[:notice] = "Sorry something went wrong..."
        redirect_to root_path
      end
    end
  end

  def privacy
  end

  def clear_messages
    @messages = Message.all
    @messages.each do |m|
      m.destroy
    end
    Image.all.map(&:destroy)
    redirect_to root_path
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email, :description)
  end
end

app/views/home/index.html.erb
<% if flash[:notice].present? %>
  <p class="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<div class="modal fade" id="modal-contact">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= form_for @subscriber, url: create_subscriber_home_index_path,
            method: :post do |f| %>
            <%= f.email_field :email, required: true, placeholder: "Email",
            class: "field email"%>
            <%= f.text_field :description, placeholder: "Tell me more",
            class: "field description" %>
            <%= f.submit "Send", class: "submit" %>
          <% end %>
          <a href="/privacy">Privacy policy</a>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row main-row">
  <a href="#" class="left top-link">Download app</a>
  <a href="#" class="run_contactModal right top-link">Contact us</a>

  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-12 left col"></div>
  <div class="col-lg-8 col-md-8 col-sm-10 col-xs-12 center col">
    <div class="center-container">
      <p>Netwrk stories</p>
      <button type="button" name="stories"></button>
    </div>
    <div id="stories">
      <%= form_for @subscriber, url: create_subscriber_home_index_path,
        method: :post do |f| %>
        <%= f.email_field :email, required: true, placeholder: "Email to subscribe",
        class: "field email"%>
        <%= f.submit "SEND", class: "submit" %>
      <% end %>
      <h3>Some header</h3>
      <div class="stories-list">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-1 col-xs-12 right col"></div>
</div>

app/views/home/privacy.html.erb
<div class="container">
  <h1>Privacy policy</h1>
<p><span style="font-weight: 400;">Netwrk is an open platform that promotes all social media that are connected to us, and that we believe are good for the world. Facebook is the first thing you see on our profile, and we hope that people will use it to connect and friend others that they become aware of through our platform. Linkedin, snapchat, and Twitter can all be connected to a person&rsquo;s profile in similar fashion. Your profile becomes a way for anyone to find you on all connected social media. These posts are able to be shared from your profile, and when clicked on, will go to the corresponding platform, therefore promoting your profile on it and also the platform itself. We&rsquo;re trying to be cool with everyone out there, giving you the best local experience possible!</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">The use of this data is specified below. Yes, it is natural that you will be sharing some information with us and that it will affect your privacy. So we want to be very clear about how we use the information we collect, who we share it with, and where it can go after it comes on our platform. To be brief, we use the information to provide the best local products and services out there that we continually improve. </span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Your casts cannot go outside an area unless it is deemed legendary. Hey, thats a good thing, but with it also comes the potential that it can be seen nationally by anyone outside that spot. Hanging something undercover is not possible to share or be sent outside where it was posted unless another person takes a picture of it. </span><span style="font-weight: 400;">It&rsquo;s also possible, as with any digital information, that someone might be able to access messages forensically or find them in a device&rsquo;s temporary storage. </span><span style="font-weight: 400;">So when it comes to sharing outside content or posting your own, you can be rest assured it will not be taken outside of these bounds. </span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">If you have any questions about this policy, feel free to contact us.</span></p>
<p><br /><br /></p>
<h2><strong>Full policy</strong></h2>
<p>&nbsp;</p>
<h2><strong>Information we collect</strong></h2>
<p><span style="font-weight: 400;">Among the types of Information that netwrk collects, by itself or through third parties, there are: geographic position, email address, first and last name, and your phone number. Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually when we gather it. The information may be freely provided by you, or collected automatically when using netwrk.</span></p>
<p><span style="font-weight: 400;">Any use of Cookies - or of other tracking tools - by this Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify you and remember their preferences, for the sole purpose of providing the service required.</span></p>
<p><span style="font-weight: 400;">Failure to provide certain Personal Data may make it impossible for netwrk to provide its services.</span></p>
<p><span style="font-weight: 400;">You are responsible for any information of third parties obtained, published or shared through netwrk and confirm the third party's consent to provide the information to netwrk.</span></p>
<p>&nbsp;</p>
<h3><strong>Methods of processing</strong></h3>
<p><span style="font-weight: 400;">Things get a little technical here (welcome to the world of technology!).</span></p>
<p><span style="font-weight: 400;">The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.</span></p>
<p><span style="font-weight: 400;">The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Data Controller, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of the site (administration, sales, marketing, legal, system administration) or external parties (such as third party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Data Controller at any time.</span></p>
<h3><strong>Place</strong></h3>
<p><span style="font-weight: 400;">The Data is processed at the Data Controller's operating offices and in any other places where the parties involved with the processing are located. For further information, please contact us.</span></p>
<h3><strong>Retention time</strong></h3>
<p><span style="font-weight: 400;">The Data is kept for the time necessary to provide the service requested, or stated by the purposes outlined in this document, and the you can always request that the Data Controller suspend or remove the data.</span></p>
<p>&nbsp;</p>
<h2><strong>The use of the collected Data</strong></h2>
<p><span style="font-weight: 400;">The information collected from you allows us to provide the best services and product possible. Specifically, but not limited to, the following purposes: Access to third party accounts, Location-based interactions and Contacting you through e-mail or phone.</span></p>
<p><span style="font-weight: 400;">The Personal Data used for each purpose is outlined in the following specific sections.</span></p>
<p>&nbsp;</p>
<h2><strong>Facebook and other social media permissions asked by this Application</strong></h2>
<p><span style="font-weight: 400;">This Application may ask for some Facebook permissions allowing it to perform actions with the User's Facebook account and to retrieve information, including Personal Data, from it. Other social media like Twitter, snapchat, or linkedin can have the same or similar permissions.</span></p>
<p><span style="font-weight: 400;">For more information about the following permissions, refer to the </span><a href="https://developers.facebook.com/docs/authentication/permissions/"><span style="font-weight: 400;">Facebook permissions documentation</span></a><span style="font-weight: 400;"> and to the </span><a href="https://www.facebook.com/about/privacy/"><span style="font-weight: 400;">Facebook privacy policy</span></a><span style="font-weight: 400;">, along with any other social permissions documentation or privacy policies.</span></p>
<p><span style="font-weight: 400;">The permissions asked are the following:</span></p>
<h3><strong>Basic information</strong></h3>
<p><span style="font-weight: 400;">By default, this includes certain your information such as id, name, picture, gender, and locale. Certain connections, such as the Friends, are also available. If you have made more information public, it will be available.</span></p>
<h3><strong>Access Friend Lists</strong></h3>
<p><span style="font-weight: 400;">Provides access to any friend lists you have created.</span></p>
<h3><strong>Interests</strong></h3>
<p><span style="font-weight: 400;">Provides access to your list of interests.</span></p>
<h3><strong>News Feed and Wall</strong></h3>
<p><span style="font-weight: 400;">Provides access to all the posts in the your news feed and enables netwrk to perform searches against it.</span></p>
<h3><strong>Publish App Activity</strong></h3>
<p><span style="font-weight: 400;">Allows the app to publish to the Open Graph using Built-in Actions, Achievements, Scores, or Custom Actions. The app can also publish other activity which is detailed in the Facebook's Publishing Permissions document.</span></p>
<h3><strong>Publish to the Wall</strong></h3>
<p><span style="font-weight: 400;">Enables the app to post content, comments, and likes to your stream and to the streams of your friends.</span></p>
<h2><strong>Detailed information on the processing of Personal Data</strong></h2>
<p><span style="font-weight: 400;">Personal Data is collected for the following purposes and using the following services:</span></p>
<ul>
<li style="font-weight: 400;">
<h3><strong>Access to third party accounts</strong></h3>
</li>
<li style="font-weight: 400;">
<h3><strong>Contacting the User</strong></h3>
</li>
<li style="font-weight: 400;">
<h3><strong>Location-based interactions</strong></h3>
</li>
</ul>
<h2><strong>Additional information about Data collection and processing</strong></h2>
<h2><strong>Third-Party Content and Integrations</strong></h2>
<h3><span style="font-weight: 400;">The services may also contain third-party links and search results, include third-party integrations, or offer a co-branded or third-party-branded service. Through these links, third-party integrations, and co-branded or third-party-branded services, you may be providing information (including personal information) directly to the third party, us, or both. You acknowledge and agree that we are not responsible for how those third parties collect or use your information. As always, we encourage you to review the privacy policies of every third-party website or service that you visit or use, including those third parties you interact with through our services.</span></h3>
<p><br /><br /><br /></p>
<h3><strong>Legal action</strong></h3>
<p><span style="font-weight: 400;">The User's Personal Data may be used for legal purposes by netwrk, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services.</span></p>
<p><span style="font-weight: 400;">The User declares to be aware that netwrk may be required to reveal personal data upon request of public authorities.</span></p>
<h3><strong>Additional information about User's Personal Data</strong></h3>
<p><span style="font-weight: 400;">In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular services or the collection and processing of Personal Data upon request.</span></p>
<h3><strong>System logs and maintenance</strong></h3>
<p><span style="font-weight: 400;">For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System logs) or use for this purpose other Personal Data (such as IP Address).</span></p>
<h3><strong>Information not contained in this policy</strong></h3>
<p><span style="font-weight: 400;">More details concerning the collection or processing of information may be requested from netwrk at any time. Please see the contact information at the beginning of this document.</span></p>
<h3><strong>The rights of Users</strong></h3>
<p><span style="font-weight: 400;">You have the right, at any time, to know whether your information has been stored and can consult the netwrk to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to us. To determine whether this application or any of the third party services it uses honor the &ldquo;Do Not Track&rdquo; requests, please read their privacy policies or contact us.</span></p>
<h3><strong>Changes to this privacy policy</strong></h3>
<p><span style="font-weight: 400;">Netwrk reserves the right to make changes to this privacy policy at any time by giving notice to its people on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If someone objects to any of the changes to the Policy, theyr must cease using netwrk and can request that we remove their ifo. Unless stated otherwise, the then-current privacy policy applies to all information we have about our people.</span></p>
<h3><strong>Information about this privacy policy</strong></h3>
<p><span style="font-weight: 400;">Netwrk is responsible for this privacy policy. Any questions, feel free to contact us.</span></p>
</div>